/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.alexapps.jardup.util;

import org.junit.Test;

import static org.junit.Assert.assertArrayEquals;

public class ArgParserTest {
    @Test public void readRootsFromArgs() {
        ArgParser parser = new ArgParser("folder1", "folder2");
        assertArrayEquals(new String[] {"folder1", "folder2"}, parser.getRoots().toArray());
    }
}
