/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.alexapps.jardup.util;

import org.junit.Test;

import static org.junit.Assert.*;

public class SettingsTest {
    @Test public void readRootsFromArgs() {
        Settings settings = new Settings("folder1", "folder2");
        assertArrayEquals(new String[] {"folder1", "folder2"}, settings.getRoots().toArray());
    }

    @Test public void excludeJars() {
        Settings settings = new Settings("--exclude-jar=.bcd[0-9].jar");
        assertFalse(settings.excludeJar("abcd1"));
        assertFalse(settings.excludeJar("abcd"));
        assertFalse(settings.excludeJar("bcd1"));
        assertTrue(settings.excludeJar("abcd1.jar"));
        assertFalse(settings.excludeJar("bcd.jar"));
    }
}
